# Special groups: all, creature, boss
groups:
  Creature_Valheim:
  - Abomination
  - Bat
  - Blob
  - BlobElite
  - BlobTar
  - Boar
  - Boar_piggy
  - Bonemass
  - Chicken
  - Deathsquito
  - Deer
  - Dragon
  - Draugr
  - Draugr_Elite
  - Draugr_Ranged
  - Dverger
  - DvergerMage
  - DvergerMageFire
  - DvergerMageIce
  - DvergerMageSupport
  - DvergerTest
  - Eikthyr
  - Fenring
  - Fenring_Cultist
  - gd_king
  - Ghost
  - Gjall
  - Goblin
  - GoblinArcher
  - GoblinBrute
  - GoblinKing
  - GoblinShaman
  - Greydwarf
  - Greydwarf_Elite
  - Greydwarf_Shaman
  - Greyling
  - Hare
  - Hatchling
  - Hen
  - Hive
  - Leech
  - Leech_cave
  - Lox
  - Lox_Calf
  - Mistile
  - Neck
  - Player
  - Seeker
  - SeekerBrood
  - SeekerBrute
  - SeekerQueen
  - Serpent
  - Skeleton
  - Skeleton_Friendly
  - Skeleton_NoArcher
  - Skeleton_Poison
  - StoneGolem
  - Surtling
  - TentaRoot
  - TheHive
  - Tick
  - TrainingDummy
  - Troll
  - Ulv
  - Wolf
  - Wolf_cub
  - Wraith
