groups:
  Material_Valheim:
  - Acorn
  - Amber
  - AmberPearl
  - AncientSeed
  - Barley
  - BarleyFlour
  - BarleyWineBase
  - BeechSeeds
  - Bilebag
  - BirchSeeds
  - BlackCore
  - BlackMarble
  - BlackMetal
  - BlackMetalScrap
  - Bloodbag
  - BoneFragments
  - BreadDough
  - Bronze
  - BronzeNails
  - BronzeScrap
  - BugMeat
  - Carapace
  - CarrotSeeds
  - Chain
  - ChickenMeat
  - Chitin
  - Coal
  - Coins
  - Copper
  - CopperOre
  - CopperScrap
  - Crystal
  - Dandelion
  - DeerHide
  - DeerMeat
  - DragonTear
  - DvergrKeyFragment
  - DvergrNeedle
  - Eitr
  - ElderBark
  - Entrails
  - Feathers
  - FineWood
  - FirCone
  - FishAndBreadUncooked
  - FishAnglerRaw
  - FishRaw
  - Flametal
  - FlametalOre
  - Flax
  - Flint
  - FreezeGland
  - GiantBloodSack
  - GreydwarfEye
  - Guck
  - HardAntler
  - HareMeat
  - Honey
  - HoneyGlazedChickenUncooked
  - Iron
  - IronNails
  - IronOre
  - IronScrap
  - JuteBlue
  - JuteRed
  - Larva
  - LeatherScraps
  - LinenThread
  - LoxMeat
  - LoxPelt
  - LoxPieUncooked
  - MagicallyStuffedShroomUncooked
  - Mandible
  - MeadBaseEitrMinor
  - MeadBaseFrostResist
  - MeadBaseHealthMajor
  - MeadBaseHealthMedium
  - MeadBaseHealthMinor
  - MeadBasePoisonResist
  - MeadBaseStaminaLingering
  - MeadBaseStaminaMedium
  - MeadBaseStaminaMinor
  - MeadBaseTasty
  - MeatPlatterUncooked
  - MechanicalSpring
  - MisthareSupremeUncooked
  - NeckTail
  - Needle
  - Obsidian
  - OnionSeeds
  - Ooze
  - PineCone
  - QueenBee
  - QueenDrop
  - RawMeat
  - Resin
  - Root
  - RoundLog
  - Ruby
  - Sap
  - ScaleHide
  - SerpentMeat
  - SerpentScale
  - SharpeningStone
  - Silver
  - SilverNecklace
  - SilverOre
  - Softtissue
  - Stone
  - SurtlingCore
  - Tar
  - Thistle
  - Thunderstone
  - Tin
  - TinOre
  - TrollHide
  - TurnipSeeds
  - VegvisirShard_Bonemass
  - Wisp
  - WitheredBone
  - WolfClaw
  - WolfFang
  - WolfHairBundle
  - WolfMeat
  - WolfPelt
  - Wood
  - YagluthDrop
  - YggdrasilWood
  - YmirRemains
  Consumable_Valheim:
  - BarleyWine
  - BlackSoup
  - BloodPudding
  - Blueberries
  - BoarJerky
  - Bread
  - Carrot
  - CarrotSoup
  - Cloudberry
  - CookedBugMeat
  - CookedChickenMeat
  - CookedDeerMeat
  - CookedEgg
  - CookedHareMeat
  - CookedLoxMeat
  - CookedMeat
  - CookedWolfMeat
  - DeerStew
  - Eyescream
  - FishAndBread
  - FishCooked
  - FishWraps
  - HealthUpgrade_Bonemass
  - HealthUpgrade_GDKing
  - HoneyGlazedChicken
  - LoxPie
  - MaceBronze
  - MaceIron
  - MaceSilver
  - MagicallyStuffedShroom
  - MeadEitrMinor
  - MeadFrostResist
  - MeadHealthMajor
  - MeadHealthMedium
  - MeadHealthMinor
  - MeadPoisonResist
  - MeadStaminaLingering
  - MeadStaminaMedium
  - MeadStaminaMinor
  - MeadTasty
  - MeatPlatter
  - MinceMeatSauce
  - MisthareSupreme
  - Mushroom
  - MushroomBlue
  - MushroomJotunPuffs
  - MushroomMagecap
  - MushroomOmelette
  - MushroomYellow
  - NeckTailGrilled
  - Onion
  - OnionSoup
  - Pukeberries
  - QueensJam
  - Raspberry
  - RottenMeat
  - RoyalJelly
  - Salad
  - Sausages
  - SeekerAspic
  - SerpentMeatCooked
  - SerpentStew
  - ShocklateSmoothie
  - StaminaUpgrade_Greydwarf
  - StaminaUpgrade_Troll
  - StaminaUpgrade_Wraith
  - Turnip
  - TurnipStew
  - WolfJerky
  - WolfMeatSkewer
  - YggdrasilPorridge
  Chest_Valheim:
  - ArmorBronzeChest
  - ArmorCarapaceChest
  - ArmorFenringChest
  - ArmorIronChest
  - ArmorLeatherChest
  - ArmorMageChest
  - ArmorPaddedCuirass
  - ArmorRagsChest
  - ArmorRootChest
  - ArmorTrollLeatherChest
  - ArmorWolfChest
  Legs_Valheim:
  - ArmorBronzeLegs
  - ArmorCarapaceLegs
  - ArmorFenringLegs
  - ArmorIronLegs
  - ArmorLeatherLegs
  - ArmorMageLegs
  - ArmorPaddedGreaves
  - ArmorRagsLegs
  - ArmorRootLegs
  - ArmorTrollLeatherLegs
  - ArmorWolfLegs
  Ammo_Valheim:
  - ArrowBronze
  - ArrowCarapace
  - ArrowFire
  - ArrowFlint
  - ArrowFrost
  - ArrowIron
  - ArrowNeedle
  - ArrowObsidian
  - ArrowPoison
  - ArrowSilver
  - ArrowWood
  - BoltBlackmetal
  - BoltBone
  - BoltCarapace
  - BoltIron
  - draugr_arrow
  TwoHandedWeapon_Valheim:
  - AtgeirBlackmetal
  - AtgeirBronze
  - AtgeirHimminAfl
  - AtgeirIron
  - Battleaxe
  - BattleaxeCrystal
  - KnifeSkollAndHati
  - PickaxeBlackMetal
  - PickaxeBronze
  - PickaxeIron
  - PickaxeStone
  - SledgeCheat
  - SledgeDemolisher
  - SledgeIron
  - SledgeStagbreaker
  - StaffFireball
  - StaffIceShards
  - StaffShield
  - THSwordKrom
  OneHandedWeapon_Valheim:
  - AxeBlackMetal
  - AxeBronze
  - AxeFlint
  - AxeIron
  - AxeJotunBane
  - AxeStone
  - BombBile
  - BombOoze
  - Club
  - DvergerArbalest_shoot
  - FistFenrirClaw
  - KnifeBlackMetal
  - KnifeButcher
  - KnifeChitin
  - KnifeCopper
  - KnifeFlint
  - KnifeSilver
  - MaceNeedle
  - PickaxeAntler
  - PlayerUnarmed
  - SpearBronze
  - SpearCarapace
  - SpearChitin
  - SpearElderbark
  - SpearFlint
  - SpearWolfFang
  - SwordBlackmetal
  - SwordBronze
  - SwordCheat
  - SwordIron
  - SwordIronFire
  - SwordMistwalker
  - SwordSilver
  - Tankard
  - Tankard_dvergr
  - TankardAnniversary
  - TankardOdin
  Utility_Valheim:
  - BeltStrength
  - Demister
  - DvergerArbalest
  - DvergerStaffSupport
  - Wishbone
  Bow_Valheim:
  - Bow
  - BowDraugrFang
  - BowFineWood
  - BowHuntsman
  - BowSpineSnap
  - CrossbowArbalest
  Shoulder_Valheim:
  - CapeDeerHide
  - CapeFeather
  - CapeLinen
  - CapeLox
  - CapeOdin
  - CapeTest
  - CapeTrollHide
  - CapeWolf
  Misc_Valheim:
  - ChickenEgg
  - CryptKey
  - DragonEgg
  - DvergrKey
  - GoblinTotem
  - SaddleLox
  FishingBait_Valheim:
  - FishingBait
  - FishingBaitAshlands
  - FishingBaitCave
  - FishingBaitDeepNorth
  - FishingBaitForest
  - FishingBaitMistlands
  - FishingBaitOcean
  - FishingBaitPlains
  - FishingBaitSwamp
  Tool_Valheim:
  - Cultivator
  - Hammer
  - Hoe
  - FishingRod
  Helmet_Valheim:
  - HelmetBronze
  - HelmetCarapace
  - HelmetDrake
  - HelmetDverger
  - HelmetFenring
  - HelmetFishingHat
  - HelmetIron
  - HelmetLeather
  - HelmetMage
  - HelmetMidsummerCrown
  - HelmetOdin
  - HelmetPadded
  - HelmetRoot
  - HelmetTrollLeather
  - HelmetYule
  Torch_Valheim:
  - Lantern
  - Torch
  - TorchMist
  Shield_Valheim:
  - ShieldBanded
  - ShieldBlackmetal
  - ShieldBlackmetalTower
  - ShieldBoneTower
  - ShieldBronzeBuckler
  - ShieldCarapace
  - ShieldCarapaceBuckler
  - ShieldIronBuckler
  - ShieldIronSquare
  - ShieldIronTower
  - ShieldKnight
  - ShieldSerpentscale
  - ShieldSilver
  - ShieldWood
  - ShieldWoodTower
  TwoHandedWeaponLeft_Valheim:
  - StaffSkeleton
  Trophie_Valheim:
  - TrophyAbomination
  - TrophyBlob
  - TrophyBoar
  - TrophyBonemass
  - TrophyCultist
  - TrophyDeathsquito
  - TrophyDeer
  - TrophyDragonQueen
  - TrophyDraugr
  - TrophyDraugrElite
  - TrophyDraugrFem
  - TrophyDvergr
  - TrophyEikthyr
  - TrophyFenring
  - TrophyForestTroll
  - TrophyFrostTroll
  - TrophyGjall
  - TrophyGoblin
  - TrophyGoblinBrute
  - TrophyGoblinKing
  - TrophyGoblinShaman
  - TrophyGreydwarf
  - TrophyGreydwarfBrute
  - TrophyGreydwarfShaman
  - TrophyGrowth
  - TrophyHare
  - TrophyHatchling
  - TrophyLeech
  - TrophyLox
  - TrophyNeck
  - TrophySeeker
  - TrophySeekerBrute
  - TrophySeekerQueen
  - TrophySerpent
  - TrophySGolem
  - TrophySkeleton
  - TrophySkeletonPoison
  - TrophySurtling
  - TrophyTheElder
  - TrophyTick
  - TrophyUlv
  - TrophyWolf
  - TrophyWraith
  AmmoNonEquipable_Valheim:
  - TurretBolt
  - TurretBoltWood














